defaults:
  - _self_
  - gen_model: large_maf
  - disc_model: mlp

hydra:
  sweeper:
    max_batch_size: 1

experiment:
  output_folder: models/
  relabel_with_disc_model: true
  seed: 0

dataset:
  _target_: counterfactuals.datasets.FileDataset
  config_path: config/datasets/blobs.yaml

disc_model:
  train_model: true
  epochs: 5000
  batch_size: 128
  patience: 300
  lr: 0.001

gen_model:
  train_model: true
  batch_size: 1024
  epochs: 2000
  patience: 100
  lr: 0.003
  noise_lvl: 0.02

tabdce:
  k_neighbors: 15
  search_method: knn
  batch_size: 512
  epochs: 300
  lr: 0.001
  T: 1000
  hidden_dim: 256
  use_gpu: false

counterfactuals_params:
  cf_method:
    _target_: counterfactuals.cf_methods.local_methods.tabdce.tabdce.TabDCE
  target_class: 0
  batch_size: 512
  cf_samples_per_factual: 5
  log_prob_quantile: 0.25
