defaults:
  - _self_
  - gen_model: large_maf
  - disc_model: nn_regression

hydra:
  sweeper:
    max_batch_size: 1

experiment:
  output_folder: models/
  relabel_with_disc_model: true
  num_folds: 5

dataset:
  _target_: counterfactuals.datasets.RegressionFileDataset
  config_path: config/datasets/toy_regression.yaml

disc_model:
  train_model: false
  epochs: 2000
  batch_size: 512
  patience: 300
  lr: 0.001

gen_model:
  train_model: false
  batch_size: 512
  epochs: 2000
  patience: 50
  lr: 0.001
  noise_lvl: 0.03

counterfactuals_params:
  target_change: 0.2
  cf_method:
    _target_: counterfactuals.cf_methods.regression_ppcef.CEARM
  epochs: 3000
  batch_size: 8096
  lr: 0.001
  alpha: 100
  patience: 300
  log_prob_quantile: 0.25
  disc_loss:
    # _target_: counterfactuals.losses.MulticlassDiscLoss
    _target_: counterfactuals.losses.ThresholdRegressionLoss
