raw_data_path: "data/adult.csv"
features: [
  "age",
  "hours_per_week",
  "workclass",
  "education",
  "marital_status",
  "occupation",
  "race",
  "gender"
]
continuous_features: [
  "age",
  "hours_per_week"
]
categorical_features: [
  "workclass",
  "education",
  "marital_status",
  "occupation",
  "race",
  "gender"
]
feature_config:
  "age":
    actionable: true
    bottom_limit: 18
    top_limit: 90
  "hours_per_week":
    actionable: true
    bottom_limit: 1
    top_limit: 99
  "workclass":
    actionable: true
  "education":
    actionable: true
  "marital_status":
    actionable: true
  "occupation":
    actionable: true
  "race":
    actionable: false  # Protected attribute
  "gender":
    actionable: false  # Protected attribute
target: "income"