raw_data_path: "data/blobs.csv"
features: ["0", "1"]
continuous_features: ["0", "1"]
categorical_features: []
feature_config:
  "0":
    actionable: true
  "1":
    actionable: true
initial_transforms:
  - name: filter_classes
    params:
      include_values:
        - 0
        - 1
      target_column: "2"
target: "2"
