raw_data_path: 'data/digits.csv'
features:
- pixel_0_0
- pixel_0_1
- pixel_0_2
- pixel_0_3
- pixel_0_4
- pixel_0_5
- pixel_0_6
- pixel_0_7
- pixel_1_0
- pixel_1_1
- pixel_1_2
- pixel_1_3
- pixel_1_4
- pixel_1_5
- pixel_1_6
- pixel_1_7
- pixel_2_0
- pixel_2_1
- pixel_2_2
- pixel_2_3
- pixel_2_4
- pixel_2_5
- pixel_2_6
- pixel_2_7
- pixel_3_0
- pixel_3_1
- pixel_3_2
- pixel_3_3
- pixel_3_4
- pixel_3_5
- pixel_3_6
- pixel_3_7
- pixel_4_0
- pixel_4_1
- pixel_4_2
- pixel_4_3
- pixel_4_4
- pixel_4_5
- pixel_4_6
- pixel_4_7
- pixel_5_0
- pixel_5_1
- pixel_5_2
- pixel_5_3
- pixel_5_4
- pixel_5_5
- pixel_5_6
- pixel_5_7
- pixel_6_0
- pixel_6_1
- pixel_6_2
- pixel_6_3
- pixel_6_4
- pixel_6_5
- pixel_6_6
- pixel_6_7
- pixel_7_0
- pixel_7_1
- pixel_7_2
- pixel_7_3
- pixel_7_4
- pixel_7_5
- pixel_7_6
- pixel_7_7
- target
continuous_features:
- pixel_0_0
- pixel_0_1
- pixel_0_2
- pixel_0_3
- pixel_0_4
- pixel_0_5
- pixel_0_6
- pixel_0_7
- pixel_1_0
- pixel_1_1
- pixel_1_2
- pixel_1_3
- pixel_1_4
- pixel_1_5
- pixel_1_6
- pixel_1_7
- pixel_2_0
- pixel_2_1
- pixel_2_2
- pixel_2_3
- pixel_2_4
- pixel_2_5
- pixel_2_6
- pixel_2_7
- pixel_3_0
- pixel_3_1
- pixel_3_2
- pixel_3_3
- pixel_3_4
- pixel_3_5
- pixel_3_6
- pixel_3_7
- pixel_4_0
- pixel_4_1
- pixel_4_2
- pixel_4_3
- pixel_4_4
- pixel_4_5
- pixel_4_6
- pixel_4_7
- pixel_5_0
- pixel_5_1
- pixel_5_2
- pixel_5_3
- pixel_5_4
- pixel_5_5
- pixel_5_6
- pixel_5_7
- pixel_6_0
- pixel_6_1
- pixel_6_2
- pixel_6_3
- pixel_6_4
- pixel_6_5
- pixel_6_6
- pixel_6_7
- pixel_7_0
- pixel_7_1
- pixel_7_2
- pixel_7_3
- pixel_7_4
- pixel_7_5
- pixel_7_6
- pixel_7_7
categorical_features: []
feature_config:
  pixel_0_0:
    actionable: true
  pixel_0_1:
    actionable: true
  pixel_0_2:
    actionable: true
  pixel_0_3:
    actionable: true
  pixel_0_4:
    actionable: true
  pixel_0_5:
    actionable: true
  pixel_0_6:
    actionable: true
  pixel_0_7:
    actionable: true
  pixel_1_0:
    actionable: true
  pixel_1_1:
    actionable: true
  pixel_1_2:
    actionable: true
  pixel_1_3:
    actionable: true
  pixel_1_4:
    actionable: true
  pixel_1_5:
    actionable: true
  pixel_1_6:
    actionable: true
  pixel_1_7:
    actionable: true
  pixel_2_0:
    actionable: true
  pixel_2_1:
    actionable: true
  pixel_2_2:
    actionable: true
  pixel_2_3:
    actionable: true
  pixel_2_4:
    actionable: true
  pixel_2_5:
    actionable: true
  pixel_2_6:
    actionable: true
  pixel_2_7:
    actionable: true
  pixel_3_0:
    actionable: true
  pixel_3_1:
    actionable: true
  pixel_3_2:
    actionable: true
  pixel_3_3:
    actionable: true
  pixel_3_4:
    actionable: true
  pixel_3_5:
    actionable: true
  pixel_3_6:
    actionable: true
  pixel_3_7:
    actionable: true
  pixel_4_0:
    actionable: true
  pixel_4_1:
    actionable: true
  pixel_4_2:
    actionable: true
  pixel_4_3:
    actionable: true
  pixel_4_4:
    actionable: true
  pixel_4_5:
    actionable: true
  pixel_4_6:
    actionable: true
  pixel_4_7:
    actionable: true
  pixel_5_0:
    actionable: true
  pixel_5_1:
    actionable: true
  pixel_5_2:
    actionable: true
  pixel_5_3:
    actionable: true
  pixel_5_4:
    actionable: true
  pixel_5_5:
    actionable: true
  pixel_5_6:
    actionable: true
  pixel_5_7:
    actionable: true
  pixel_6_0:
    actionable: true
  pixel_6_1:
    actionable: true
  pixel_6_2:
    actionable: true
  pixel_6_3:
    actionable: true
  pixel_6_4:
    actionable: true
  pixel_6_5:
    actionable: true
  pixel_6_6:
    actionable: true
  pixel_6_7:
    actionable: true
  pixel_7_0:
    actionable: true
  pixel_7_1:
    actionable: true
  pixel_7_2:
    actionable: true
  pixel_7_3:
    actionable: true
  pixel_7_4:
    actionable: true
  pixel_7_5:
    actionable: true
  pixel_7_6:
    actionable: true
  pixel_7_7:
    actionable: true
target: target
