raw_data_path: "data/heloc.csv"
features: [
  "ExternalRiskEstimate",
  "MSinceOldestTradeOpen", 
  "MSinceMostRecentTradeOpen",
  "AverageMInFile",
  "NumSatisfactoryTrades",
  "NumTrades60Ever2DerogPubRec",
  "NumTrades90Ever2DerogPubRec",
  "PercentTradesNeverDelq",
  "MSinceMostRecentDelq",
  "MaxDelq2PublicRecLast12M",
  "MaxDelqEver",
  "NumTotalTrades",
  "NumTradesOpeninLast12M",
  "PercentInstallTrades",
  "MSinceMostRecentInqexcl7days",
  "NumInqLast6M",
  "NumInqLast6Mexcl7days",
  "NetFractionRevolvingBurden",
  "NetFractionInstallBurden",
  "NumRevolvingTradesWBalance",
  "NumInstallTradesWBalance",
  "NumBank2NatlTradesWHighUtilization",
  "PercentTradesWBalance"
]
continuous_features: [
  "ExternalRiskEstimate",
  "MSinceOldestTradeOpen", 
  "MSinceMostRecentTradeOpen",
  "AverageMInFile",
  "NumSatisfactoryTrades",
  "NumTrades60Ever2DerogPubRec",
  "NumTrades90Ever2DerogPubRec",
  "PercentTradesNeverDelq",
  "MSinceMostRecentDelq",
  "MaxDelq2PublicRecLast12M",
  "MaxDelqEver",
  "NumTotalTrades",
  "NumTradesOpeninLast12M",
  "PercentInstallTrades",
  "MSinceMostRecentInqexcl7days",
  "NumInqLast6M",
  "NumInqLast6Mexcl7days",
  "NetFractionRevolvingBurden",
  "NetFractionInstallBurden",
  "NumRevolvingTradesWBalance",
  "NumInstallTradesWBalance",
  "NumBank2NatlTradesWHighUtilization",
  "PercentTradesWBalance"
]
categorical_features: []
feature_config:
  "ExternalRiskEstimate":
    actionable: true
  "MSinceOldestTradeOpen":
    actionable: true
  "MSinceMostRecentTradeOpen":
    actionable: true
  "AverageMInFile":
    actionable: true
  "NumSatisfactoryTrades":
    actionable: true
  "NumTrades60Ever2DerogPubRec":
    actionable: true
  "NumTrades90Ever2DerogPubRec":
    actionable: true
  "PercentTradesNeverDelq":
    actionable: true
  "MSinceMostRecentDelq":
    actionable: true
  "MaxDelq2PublicRecLast12M":
    actionable: true
  "MaxDelqEver":
    actionable: true
  "NumTotalTrades":
    actionable: true
  "NumTradesOpeninLast12M":
    actionable: true
  "PercentInstallTrades":
    actionable: true
  "MSinceMostRecentInqexcl7days":
    actionable: true
  "NumInqLast6M":
    actionable: true
  "NumInqLast6Mexcl7days":
    actionable: true
  "NetFractionRevolvingBurden":
    actionable: true
  "NetFractionInstallBurden":
    actionable: true
  "NumRevolvingTradesWBalance":
    actionable: true
  "NumInstallTradesWBalance":
    actionable: true
  "NumBank2NatlTradesWHighUtilization":
    actionable: true
  "PercentTradesWBalance":
    actionable: true
target: "RiskPerformance"
target_mapping:
  "Bad": 0
  "Good": 1
initial_transforms:
  - name: reorder_columns
  - name: dropna
  - name: convert_to_numeric
    params:
      errors: coerce
  - name: one_hot_encode
    params:
      drop_first: false
