raw_data_path: data/regression/winequality.csv
features:
- fixed acidity
- volatile acidity
- citric acid
- residual sugar
- chlorides
- free sulfur dioxide
- total sulfur dioxide
- density
- pH
- sulphates
- alcohol
continuous_features:
- fixed acidity
- volatile acidity
- citric acid
- residual sugar
- chlorides
- free sulfur dioxide
- total sulfur dioxide
- density
- pH
- sulphates
- alcohol
categorical_features: []
feature_config:
  fixed acidity:
    actionable: true
  volatile acidity:
    actionable: true
  citric acid:
    actionable: true
  residual sugar:
    actionable: true
  chlorides:
    actionable: true
  free sulfur dioxide:
    actionable: true
  total sulfur dioxide:
    actionable: true
  density:
    actionable: true
  pH:
    actionable: true
  sulphates:
    actionable: true
  alcohol:
    actionable: true
target: quality
